version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_DATABASE: Zela
      MYSQL_USER: ZelaAdmin
      MYSQL_PASSWORD: ZelaAdmin12345
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
